In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
%matplotlib inline

In [37]:
print("Pandas",pd.__version__)
print("numpy",np.__version__)
print("scikit",sklearn.__version__)

Pandas 3.0.5
numpy 2.5.2
scikit 1.9.0

In [38]:
from pathlib import Path

BASE_DIR = Path.cwd().parent
RAW_DATA_PATH = BASE_DIR/"data"/"raw"

print(RAW_DATA_PATH)

c:\Users\ykuma\OneDrive\Desktop\Financial-Transaction-Risk-Intelligence\data\raw

In [39]:
csv_files = list(RAW_DATA_PATH.glob("*csv"))

csv_files

[WindowsPath('c:/Users/ykuma/OneDrive/Desktop/Financial-Transaction-Risk-Intelligence/data/raw/PS_20174392719_1491204439457_log.csv')]

In [40]:
DATA_FILE = csv_files[0]

df = pd.read_csv(DATA_FILE)

In [41]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [42]:
df.shape

(6362620, 11)

In [43]:
print(f"Rows : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]:,}")

Rows : 6,362,620
Columns : 11

In [44]:
df.columns.tolist()

['step',
 'type',
 'amount',
 'nameOrig',
 'oldbalanceOrg',
 'newbalanceOrig',
 'nameDest',
 'oldbalanceDest',
 'newbalanceDest',
 'isFraud',
 'isFlaggedFraud']

In [45]:
df.dtypes

step                int64
type                  str
amount            float64
nameOrig              str
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest              str
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [46]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [47]:
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

step              0.0
type              0.0
amount            0.0
nameOrig          0.0
oldbalanceOrg     0.0
newbalanceOrig    0.0
nameDest          0.0
oldbalanceDest    0.0
newbalanceDest    0.0
isFraud           0.0
isFlaggedFraud    0.0
dtype: float64

In [48]:
print("Duplicate rows:", f"{df.duplicated().sum():,}")

Duplicate rows: 0

In [49]:
df["isFraud"].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [50]:
## percentage of Fraud
df["isFraud"].value_counts(normalize=True) * 100

isFraud
0    99.870918
1     0.129082
Name: proportion, dtype: float64

In [51]:
## types of transactions
df["type"].value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [52]:
df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [53]:
## uninque values 
for column in df.columns:
    print(f"{column}: {df[column].nunique():,} unique values")

step: 743 unique values
type: 5 unique values
amount: 5,316,900 unique values
nameOrig: 6,353,307 unique values
oldbalanceOrg: 1,845,844 unique values
newbalanceOrig: 2,682,586 unique values
nameDest: 2,722,362 unique values
oldbalanceDest: 3,614,697 unique values
newbalanceDest: 3,555,499 unique values
isFraud: 2 unique values
isFlaggedFraud: 2 unique values

In [54]:
fraud_rate = df["isFraud"].mean() * 100
fraud_rate

np.float64(0.12908204481801522)

In [55]:
balance_columns = [
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest"
]

In [56]:
zero_by_type = (
    df.groupby("type")[balance_columns]
      .apply(lambda x: (x == 0).mean() * 100)
      .round(2)
)

print("\nPercentage of Zero Balances by Transaction Type:")
print(zero_by_type)

Percentage of Zero Balances by Transaction Type:
          oldbalanceOrg  newbalanceOrig  oldbalanceDest  newbalanceDest
type
CASH_IN            0.96            0.00           11.69           19.36
CASH_OUT          45.85           88.72           14.49            0.51
DEBIT             14.86           28.45            0.00            1.13
PAYMENT           35.99           51.18          100.00          100.00
TRANSFER          53.06           95.97           12.22            0.97